application: udacity-testapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /wiki.*
  script: wiki.app

- url: /.*
  script: blog.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: django
  version: latest

